/*! Copyright (c) 2020 Patrick Demian; Licensed under MIT */
/** @internal */ export declare const Zero: import("chevrotain").TokenType;
/** @internal */ export declare const One: import("chevrotain").TokenType;
/** @internal */ export declare const Two: import("chevrotain").TokenType;
/** @internal */ export declare const Three: import("chevrotain").TokenType;
/** @internal */ export declare const Four: import("chevrotain").TokenType;
/** @internal */ export declare const Five: import("chevrotain").TokenType;
/** @internal */ export declare const Six: import("chevrotain").TokenType;
/** @internal */ export declare const Seven: import("chevrotain").TokenType;
/** @internal */ export declare const Eight: import("chevrotain").TokenType;
/** @internal */ export declare const Nine: import("chevrotain").TokenType;
/** @internal */ export declare const Ten: import("chevrotain").TokenType;
/** @internal */ export declare const Optional: import("chevrotain").TokenType;
/** @internal */ export declare const Match: import("chevrotain").TokenType;
/** @internal */ export declare const Then: import("chevrotain").TokenType;
/** @internal */ export declare const Anything: import("chevrotain").TokenType;
/** @internal */ export declare const Or: import("chevrotain").TokenType;
/** @internal */ export declare const And: import("chevrotain").TokenType;
/** @internal */ export declare const Word: import("chevrotain").TokenType;
/** @internal */ export declare const Digit: import("chevrotain").TokenType;
/** @internal */ export declare const Character: import("chevrotain").TokenType;
/** @internal */ export declare const Letter: import("chevrotain").TokenType;
/** @internal */ export declare const Decimal: import("chevrotain").TokenType;
/** @internal */ export declare const Integer: import("chevrotain").TokenType;
/** @internal */ export declare const Whitespace: import("chevrotain").TokenType;
/** @internal */ export declare const Boundary: import("chevrotain").TokenType;
/** @internal */ export declare const Number: import("chevrotain").TokenType;
/** @internal */ export declare const Unicode: import("chevrotain").TokenType;
/** @internal */ export declare const Using: import("chevrotain").TokenType;
/** @internal */ export declare const Global: import("chevrotain").TokenType;
/** @internal */ export declare const Multiline: import("chevrotain").TokenType;
/** @internal */ export declare const Exact: import("chevrotain").TokenType;
/** @internal */ export declare const Matching: import("chevrotain").TokenType;
/** @internal */ export declare const Not: import("chevrotain").TokenType;
/** @internal */ export declare const Between: import("chevrotain").TokenType;
/** @internal */ export declare const Tab: import("chevrotain").TokenType;
/** @internal */ export declare const Linefeed: import("chevrotain").TokenType;
/** @internal */ export declare const Group: import("chevrotain").TokenType;
/** @internal */ export declare const A: import("chevrotain").TokenType;
/** @internal */ export declare const Times: import("chevrotain").TokenType;
/** @internal */ export declare const Exactly: import("chevrotain").TokenType;
/** @internal */ export declare const Inclusive: import("chevrotain").TokenType;
/** @internal */ export declare const Exclusive: import("chevrotain").TokenType;
/** @internal */ export declare const From: import("chevrotain").TokenType;
/** @internal */ export declare const To: import("chevrotain").TokenType;
/** @internal */ export declare const Create: import("chevrotain").TokenType;
/** @internal */ export declare const Called: import("chevrotain").TokenType;
/** @internal */ export declare const Repeat: import("chevrotain").TokenType;
/** @internal */ export declare const Newline: import("chevrotain").TokenType;
/** @internal */ export declare const CarriageReturn: import("chevrotain").TokenType;
/** @internal */ export declare const CaseInsensitive: import("chevrotain").TokenType;
/** @internal */ export declare const CaseSensitive: import("chevrotain").TokenType;
/** @internal */ export declare const OrMore: import("chevrotain").TokenType;
/** @internal */ export declare const EndOfLine: import("chevrotain").TokenType;
/** @internal */ export declare const WS: import("chevrotain").TokenType;
/** @internal */ export declare const SingleLineComment: import("chevrotain").TokenType;
/** @internal */ export declare const MultilineComment: import("chevrotain").TokenType;
/** @internal */ export declare const Identifier: import("chevrotain").TokenType;
/** @internal */ export declare const NumberLiteral: import("chevrotain").TokenType;
/** @internal */ export declare const StringLiteral: import("chevrotain").TokenType;
/** @internal */ export declare const Indent: import("chevrotain").TokenType;
/** @internal */ export declare const Outdent: import("chevrotain").TokenType;
/**
 * All the tokens used
 * @internal
 */
export declare const AllTokens: import("chevrotain").TokenType[];
